name: Simple Echo Job

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  echo-job:
    runs-on: [self-hosted, trusted-agent]  # This specifies that it should run on a self-hosted runner with the trusted-agent label

    steps:
      - name: Echo Hello World
        run: echo "Hello World from Runner-Trusted-A"
