name: Hello World Workfloww

on: 
  push:
    branches:
      - main

jobs:
  echo-job:
    runs-on: [self-hosted, trusted-agent, malicious-agent]  # Specify the label of the trusted agent
    steps:
      - name: Echo Hello World
        run: echo "Hello World"
