name: Simple Echo Job

on:
  push:
    branches:
      - main  # You can change this to any branch you want

jobs:
  echo-job:
    runs-on: self-hosted  # This specifies that it should run on a self-hosted runner
    # Use both the self-hosted and trusted-agent labels together
    
    if: contains(runner.labels, 'trusted-agent')

    steps:
      - name: Echo Hello World
        run: echo "Hello World from Runner-Trusted-A"
