name: Validate Image and Runn

on:
  push:
    branches:
      - main

jobs:
  validate-image:
    runs-on: self-hosted  # Use the same label
    steps:
      - name: Clean up faulty Azure CLI sources
        run: |
          # Remove any previous erroneous azure-cli sources
          sudo rm -f /etc/apt/sources.list.d/azure-cli.list
          sudo rm -f /etc/apt/sources.list.d/azure-cli.sources

      - name: Install Azure CLI
        run: |
          # Update the package list and install prerequisites
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release

          # Use the official Azure CLI install script
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Uses the secret created earlier

      - name: Check Ubuntu Image Version
        run: |
          EXPECTED_IMAGE_VERSION="0.20240717.1811"  # Set your expected version
          CURRENT_IMAGE_VERSION=$(az vm show --resource-group Test --name VM2 --query "storageProfile.imageReference.exactVersion" -o tsv)

          if [[ "$CURRENT_IMAGE_VERSION" != "$EXPECTED_IMAGE_VERSION" ]]; then
            echo "Error: Image version does not match. Aborting."
            exit 1
          else
            echo "Image version matches. Proceeding..."
          fi

  next-stage:
    runs-on: [self-hosted, linux-runner]
    needs: validate-image
    if: success()  # Only runs if the previous job was successful
    steps:
      - name: Run Next Steps
        run: echo "Test is Successfull. Running next stages..."
