name: Hello World Pipeline

on:
  push:
    branches:
      #- main

jobs:
  hello-world-job:
    runs-on: self-hosted
    labels: trusted-agent  # Unique label for your trusted agent

    steps:
      # Step 1: Print "Hello World"
      - name: Say Hello World
        run: echo "Hello World"
