name: Agent Validation Workflow

on: 
  push:
    branches:
      - main

jobs:
  validate-agent:
    runs-on: self-hosted
    steps:
      - name: Check agent type
        run: |
          if [[ "${{ runner.labels }}" == *"malicious-agent"* ]]; then
            echo "Bad agent pipeline failed"
            exit 1
          elif [[ "${{ runner.labels }}" == *"trusted-agent"* ]]; then
            echo "Hello World"
          else
            echo "Agent type unknown, skipping"
            exit 1
          fi
        shell: bash
