name: Secure Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    # Target only the trusted agent by its label
    labels: trusted-agent

    steps:
      - name: Say Hello World
        run: echo "Hello World from trusted Runner-Trusted-A"
