# name: Hello World Workfloww

# on: 
#   push:
#     branches:
#       - main

# jobs:
#   echo-job:
#     runs-on: [self-hosted, trusted-agent, malicious-agent]  # Specify the label of the trusted agent
#     steps:
#       - name: Echo Hello World
#         run: echo "Hello World"


name: Runner Label Detection

on:
  push:
    branches:
      - main

jobs:
  check-agent:
    runs-on: self-hosted  # This runs on a self-hosted runner

    steps:
      - name: Check if it's a trusted agent
        if: contains(runner.labels, 'trusted-agent')
        run: echo "Hello, World! Trusted agent detected!"
      
      - name: Fail if it's a malicious agent
        if: contains(runner.labels, 'malicious-agent')
        run: |
          echo "Malicious agent detected!"
          exit 1  # Fail the job if malicious agent is detected
      
      - name: Default Action
        if: always()  # This runs if none of the above conditions are satisfied
        run: echo "Running on a different agent."
