name: Validate Image and Run

on:
  push:
    branches:
      - main

jobs:
  validate-image:
    runs-on: [self-hosted, linux-runner]  # Use the same label
    steps:
      - name: Install Azure CLI
        run: |
          # Update the package list and install prerequisites
          sudo apt-get update
          sudo apt-get install -y curl apt-transport-https software-properties-common

          # Import the Microsoft GPG key
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor -o /usr/share/keyrings/azure-cli.gpg

          # Add the Azure CLI APT repository
          echo "deb [signed-by=/usr/share/keyrings/azure-cli.gpg] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/azure-cli.list

          # Update the package list again and install Azure CLI
          sudo apt-get update
          sudo apt-get install -y azure-cli

      - name: Check Ubuntu Image Version
        run: |
          EXPECTED_IMAGE_VERSION="22.04.202409260"  # Set your expected version
          CURRENT_IMAGE_VERSION=$(az vm show --resource-group Test --name VM1 --query "storageProfile.imageReference.exactVersion" -o tsv)

          if [[ "$CURRENT_IMAGE_VERSION" != "$EXPECTED_IMAGE_VERSION" ]]; then
            echo "Error: Image version does not match. Aborting."
            exit 1
          else
            echo "Image version matches. Proceeding..."
          fi

  next-stage:
    runs-on: [self-hosted, linux-runner]
    needs: validate-image
    if: success()  # Only runs if the previous job was successful
    steps:
      - name: Run Next Steps
        run: echo "Running next stage..."
