name: Runner Verification Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  echo-job:
    runs-on: self-hosted  # This specifies that it should run on a self-hosted runner

    steps:
      # Step 1: Check Environment Variables for debugging
      - name: Check Environment Variables
        run: |
          echo "All Environment Variables:"
          env

      # Step 2: Verify if the runner is trusted
      - name: Verify Runner Identity
        run: |
          echo "Runner Name: ${{ github.runner.name }}"  # Use GitHub Actions context to get the runner's name
          echo "Runner Labels: ${{ toJson(github.runner.labels) }}"  # Use GitHub Actions context to get the runner's labels
          
          # Define expected values
          trusted_name="Runner-Trusted-A"  # Name of the trusted runner
          trusted_label="trusted-agent"      # Label for the trusted runner
          
          # Check if the current runner is the trusted runner
          if [[ "${{ github.runner.name }}" == "${trusted_name}" && "${{ toJson(github.runner.labels) }}" == *"${trusted_label}"* ]]; then
            echo "This is the trusted agent. Proceeding with the pipeline."
            echo "Hello World from Trusted Runner!"
          else
            echo "This is not a trusted agent. Exiting..."
            exit 1
          fi
