name: Validate Image and Run

on:
  push:
    branches:
      - main

jobs:
  validate-image:
    runs-on: [self-hosted, linux-runner]  # Use the same label
    steps:
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Check Ubuntu Image Version
        run: |
          EXPECTED_IMAGE_VERSION="22.04.202409260"  # Set your expected version
          CURRENT_IMAGE_VERSION=$(az vm show --resource-group Test --name VM1 --query "storageProfile.imageReference.exactVersion" -o tsv)

          if [[ "$CURRENT_IMAGE_VERSION" != "$EXPECTED_IMAGE_VERSION" ]]; then
            echo "Error: Image version does not match. Aborting."
            exit 1
          else
            echo "Image version matches. Proceeding..."
          fi

  next-stage:
    runs-on: [self-hosted, linux-runner]
    needs: validate-image
    if: success()  # Only runs if the previous job was successful
    steps:
      - name: Run Next Steps
        run: echo "Running next stage..."
