name: CI/CD Pipeline with Trusted and Malicious Agents Detection

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  differentiate-agents:
    runs-on: ${{ matrix.agent }}
    strategy:
      matrix:
        agent: ['self-hosted', 'Runner-A-Trusted', 'Runner-A-Malicious']
    
    steps:
      - name: Check if Runner is Trusted or Malicious
        run: |
          if [[ "${{ runner.labels }}" == *"trusted-agent"* ]]; then
            echo "Hello World"
          elif [[ "${{ runner.labels }}" == *"malicious-agent"* ]]; then
            echo "Malicious agent detected! Failing the pipeline..."
            exit 1  # Fail the pipeline for malicious-agent
          else
            echo "Unknown agent. Failing the pipeline..."
            exit 1
          fi  # Ensure the if block is closed properly
