name: Secure Pipelinee

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted/trusted-agent

  

    steps:
      - name: Say Hello World
        run: echo "Hello World from trusted Runner-Trusted-A"
