name: Validate Image and Run

on:
  push:
    branches:
      - main

jobs:
  validate-image:
    runs-on: [self-hosted, linux-runner]  # Use the same label
    steps:
      - name: Install Azure CLI
        run: |
          # Update the package list and install prerequisites
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release

          # Create a keyrings directory and add Microsoft's GPG key
          sudo mkdir -p /etc/apt/keyrings
          curl -sLS https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/keyrings/microsoft.gpg > /dev/null
          sudo chmod go+r /etc/apt/keyrings/microsoft.gpg

          # Add Azure CLI APT repository
          AZ_DIST=$(lsb_release -cs)
          echo "Types: deb
          URIs: https://packages.microsoft.com/repos/azure-cli/
          Suites: ${AZ_DIST}
          Components: main
          Architectures: $(dpkg --print-architecture)
          Signed-by: /etc/apt/keyrings/microsoft.gpg" | sudo tee /etc/apt/sources.list.d/azure-cli.sources

          # Update package list again and install Azure CLI
          sudo apt-get update
          sudo apt-get install -y azure-cli

      - name: Check Ubuntu Image Version
        run: |
          EXPECTED_IMAGE_VERSION="22.04.202409260"  # Set your expected version
          CURRENT_IMAGE_VERSION=$(az vm show --resource-group Test --name VM1 --query "storageProfile.imageReference.exactVersion" -o tsv)

          if [[ "$CURRENT_IMAGE_VERSION" != "$EXPECTED_IMAGE_VERSION" ]]; then
            echo "Error: Image version does not match. Aborting."
            exit 1
          else
            echo "Image version matches. Proceeding..."
          fi

  next-stage:
    runs-on: [self-hosted, linux-runner]
    needs: validate-image
    if: success()  # Only runs if the previous job was successful
    steps:
      - name: Run Next Steps
        run: echo "Running next stage..."
