name: Simple Echo Job

on:
  push:
    branches:
      - main  # You can change this to any branch you want

jobs:
  echo-job:
    runs-on: self-hosted  # Specify it should run on a self-hosted runner
    # Use the specific label in the runs-on line
    runs-on: [self-hosted, trusted-agent] 

    steps:
      - name: Echo Hello World
        run: echo "Hello World from Runner-Trusted-A"
