name: CI/CD Pipeline with Trusted and Malicious Agents Detection

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  differentiate-agents:
    runs-on: ${{ matrix.agent }}
    strategy:
      matrix:
        agent: ['self-hosted', 'Runneer-Trusted-A', 'Runner-Trusted-A']
    
    steps:
      - name: Check if Runner is Trusted or Malicious
        run: |
          if [[ "${{ matrix.agent }}" == "trusted-agent" ]]; then
            echo "This is a Trusted Agent."
            echo "agent_type=trusted" >> $GITHUB_ENV
          elif [[ "${{ matrix.agent }}" == "Untrusted" ]]; then
            echo "This is a Malicious Agent."
            echo "agent_type=malicious" >> $GITHUB_ENV
            echo "Malicious agent detected! Failing the pipeline..."
            exit 1  # This will fail the pipeline if it's a malicious agent
          else
            echo "Unknown Agent."
            exit 1
          
  run-trusted:
    needs: differentiate-agents
    if: env.agent_type == 'trusted'
    runs-on: trusted-agent
    steps:
      - name: Run tasks on Trusted Agent
        run: |
          echo "Running tasks on the Trusted Agent..."
