name: Docker Container as Agent
on: 
  push: 
    branches: 
      - main
jobs:  
  docker-agent:    
    runs-on: ubuntu-latest    
    container:      
      image: dheeman29/test:v1 # Your Docker image here
    steps:      
      # Step 1: Start container and capture its ID and SHA256      
      - name: Start container and capture IDs        
        run: |          
          # Start the container in detached mode
          docker run -d --name my-agent dheeman29/test:v1
          
          # Capture the container ID
          CONTAINER_ID=$(docker inspect --format='{{.Id}}' my-agent)
          echo "CONTAINER_ID=$CONTAINER_ID" >> $GITHUB_ENV

          # Capture the SHA256 ID of the image
          CONTAINER_SHA256=$(docker inspect --format='{{.Image}}' my-agent | sed 's/^sha256://')
          echo "CONTAINER_SHA256=$CONTAINER_SHA256" >> $GITHUB_ENV

      # Step 2: Verify the container's SHA256 ID      
      - name: Verify Container SHA256 ID        
        run: |          
          EXPECTED_SHA256="${{ secrets.CONTAINER_SHA256 }}"
          ACTUAL_SHA256="${{ env.CONTAINER_SHA256 }}"
          
          if [ "$EXPECTED_SHA256" != "$ACTUAL_SHA256" ]; then
              echo "SHA256 mismatch. Aborting."
              exit 1
          fi
          echo "SHA256 ID verified successfully."

      # Step 3: Print Hello World from the container      
      - name: Hello World        
        run: |          
          echo "Hello World from container agent!"

      # Step 4: Cleanup      
      - name: Cleanup        
        run: |          
          docker stop my-agent
          docker rm my-agent
