name: Docker Container SHA256 Check with Dynamic SHA256

on:
  push:
    branches:
      - main

jobs:
  docker_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image (Zero Trust)
        id: build_image
        run: |
          IMAGE_TAG="my-sample-image:latest"
          # Build the Docker image
          docker build -t $IMAGE_TAG .

          # Get the image SHA256 hash after building the image
          IMAGE_SHA256=$(docker inspect --format='{{.Id}}' $IMAGE_TAG)
          echo "Built image SHA256: $IMAGE_SHA256"
          
          # Output the SHA256 to be used in later steps
          echo "image_sha256=$IMAGE_SHA256" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag Docker image
        run: |
          docker tag my-sample-image ${{ secrets.DOCKER_USERNAME }}/my-sample-image:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-sample-image:latest

      - name: Run Docker container from pushed image
        run: |
          docker run -d --name my-sample-container ${{ secrets.DOCKER_USERNAME }}/my-sample-image:latest

      - name: Inspect Docker container
        id: inspect_container
        run: |
          CONTAINER_SHA256=$(docker inspect --format='{{.Image}}' my-sample-container)
          echo "Container SHA256: $CONTAINER_SHA256"
          echo "container_sha256=$CONTAINER_SHA256" >> $GITHUB_ENV

      - name: Compare image SHA256 with container SHA256 (Zero Trust)
        run: |
          IMAGE_SHA256="${{ env.image_sha256 }}"
          CONTAINER_SHA256="${{ env.container_sha256 }}"
          
          echo "Built image SHA256: $IMAGE_SHA256"
          echo "Container SHA256: $CONTAINER_SHA256"

          # Compare the two SHA256 hashes
          if [ "$IMAGE_SHA256" == "$CONTAINER_SHA256" ]; then
            echo "SHA256 matches. Success."
          else
            echo "SHA256 does not match. Failing pipeline."
            exit 1
          fi
