name: Validate Docker Container SHA256 ID

on:
  push:
    branches:
      - main

jobs:
  validate-container:
    runs-on: ubuntu-latest
    container:
      image: dheeman29/test:v1

    steps:
      # Step 1: Debug information about the environment
      - name: Check environment
        run: |
          echo "Running in container:"
          cat /proc/self/cgroup
          echo "Docker version:"
          docker --version || echo "Docker not installed or not running."

      # Step 2: Capture Docker Container SHA256 ID
      - name: Capture Docker Container SHA256 ID
        id: capture_sha256
        run: |
          # Attempt to get the container ID using a different approach
          CONTAINER_ID=$(basename $(cat /proc/self/cgroup | grep "docker" | awk -F/ '{print $3}' | head -n 1))
          
          if [ -z "$CONTAINER_ID" ]; then
            echo "Error: Unable to capture container ID."
            exit 1
          fi
          
          echo "Captured Container ID: $CONTAINER_ID"

          # Get the SHA256 ID of the container (prefix with sha256: for full digest)
          CONTAINER_SHA256=$(docker inspect --format='{{.Id}}' $CONTAINER_ID | sed 's/^sha256://')
          
          if [ -z "$CONTAINER_SHA256" ]; then
            echo "Error: Unable to capture container SHA256 ID."
            exit 1
          fi
          
          echo "Captured Container SHA256 ID: $CONTAINER_SHA256"

          # Store the SHA256 ID as a GitHub environment variable
          echo "CONTAINER_SHA256=$CONTAINER_SHA256" >> $GITHUB_ENV

      # Step 3: Validate Docker Container SHA256 ID
      - name: Validate Docker Container SHA256 ID
        run: |
          # Get the expected container SHA256 from secrets
          EXPECTED_CONTAINER_SHA256="${{ secrets.CONTAINER_SHA256 }}"

          # Validate if the captured SHA256 matches the expected SHA256
          if [[ "$CONTAINER_SHA256" != "$EXPECTED_CONTAINER_SHA256" ]]; then
            echo "Error: Docker Container SHA256 ID does not match. Aborting."
            exit 1
          fi

          echo "Docker Container SHA256 ID matches. Proceeding..."

      # Step 4: Log Node version and OS release
      - name: Log the Node version and OS release
        run: |
          node -v
          cat /etc/os-release
