name: Validate Docker Container SHA256 ID

on:
  push:
    branches:
      - main

jobs:
  validate-container:
    runs-on: ubuntu-latest
    container: dheeman29/test:v1

    steps:
      # Step 1: Capture Docker Container SHA256 ID
      - name: Capture Docker Container SHA256 ID
        run: |
          # Use the container's environment variable for its ID
          CONTAINER_ID=$(head -n 1 /proc/self/cgroup | sed 's/^.*\///' | tail -n1)
          echo "Captured Container ID: $CONTAINER_ID"
          
          # Get the container's SHA256 using the container ID (this will be its full digest if available)
          CONTAINER_SHA256=$(docker inspect --format='{{.Id}}' $CONTAINER_ID)
          echo "Captured Container SHA256 ID: $CONTAINER_SHA256"
          echo "CONTAINER_SHA256=$CONTAINER_SHA256" >> $GITHUB_ENV

      # Step 2: Validate Docker Container SHA256 ID
      - name: Validate Docker Container SHA256 ID
        run: |
          EXPECTED_CONTAINER_SHA256="${{ secrets.CONTAINER_SHA256 }}"
          if [[ "$CONTAINER_SHA256" != "$EXPECTED_CONTAINER_SHA256" ]]; then
            echo "Error: Docker Container SHA256 ID does not match. Aborting."
            exit 1
          else
            echo "Docker Container SHA256 ID matches. Proceeding..."
          fi

      # Step 3: Log Node version and OS release
      - name: Log the Node version and OS release
        run: |
          node -v
          cat /etc/os-release
