name: Docker Container as Agent
on: 
  push: 
    branches: 
      - main
jobs:  
  docker-agent:    
    runs-on: ubuntu-latest    
    container:      
      image: dheeman29/docker-cosign:v1
    steps:      
      # Step 1: Capture SHA256 ID of the Image
      - name: Capture SHA256 ID of the Image
        run: |          
          REPO_DIGESTS=$(docker inspect --format='{{.RepoDigests}}' dheeman29/docker-cosign:v1)
          if [ "$REPO_DIGESTS" == "[]" ]; then
              echo "Error: RepoDigests is empty. Cannot retrieve SHA256."
              exit 1
          fi
          CONTAINER_SHA256=$(docker inspect --format='{{index .RepoDigests 0}}' dheeman29/docker-cosign:v1 | sed 's/.*@sha256://')
          echo "CONTAINER_SHA256=$CONTAINER_SHA256" >> $GITHUB_ENV

      # Step 2: Verify Container SHA256 ID        
      - name: Verify Container SHA256 ID
        run: |          
          EXPECTED_SHA256="${{ secrets.EXPECTED_SHA256 }}"
          ACTUAL_SHA256="${{ env.CONTAINER_SHA256 }}"
          if [ "$EXPECTED_SHA256" != "$ACTUAL_SHA256" ]; then
              echo "SHA256 mismatch. Aborting."
              exit 1
          fi
          echo "SHA256 ID verified successfully."

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      # Step 4: Install Trivy
      - name: Install Trivy
        run: |
           apt-get update -y
           apt-get install wget -y
           wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.44.0_Linux-64bit.deb
           dpkg -i trivy_0.44.0_Linux-64bit.deb

      # Step 5: Sign the Container Image (using digest instead of tag)
      - name: Sign Container Image
        env:
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSPHRASE }}
        run: |
          cosign sign --key env://COSIGN_KEY dheeman29/docker-cosign@sha256:${{ env.CONTAINER_SHA256 }} --yes

      # Step 6: Public Key Creation
      - name: Public Key Creation
        env:
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSPHRASE }}
        run: |
          cosign public-key --key env://COSIGN_KEY > cosign.pub

      # Step 7: Verify Image Signature (Key-based)
      - name: Verify Image Signature (Key-based)
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          cosign verify --key cosign.pub dheeman29/docker-cosign@sha256:${{ env.CONTAINER_SHA256 }}

      # Step 8: Scan Image with Trivy for High and Critical Vulnerabilities
      - name: Scan Image with Trivy
        run: |
          trivy image --severity HIGH,CRITICAL --exit-code 0 --format json --output trivy_report.json dheeman29/docker-cosign@sha256:${{ env.CONTAINER_SHA256 }}

      # Step 9: Upload Trivy Scan Results
      - name: Upload Trivy Report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: trivy_report.json

      # Step 10: Print Hello World from the Container
      - name: Hello World        
        run: |
          echo "Hello World from container agent!"
