name: Validate Docker Container SHA256 ID

on:
  push:
    branches:
      - main

jobs:
  validate-container:
    runs-on: ubuntu-latest
    container: 
      image: dheeman29/go-web-app:10234524538
    steps:
      # Step 1: Capture Docker Container SHA256 ID
      - name: Capture Docker Container SHA256 ID
        run: |
          CONTAINER_SHA256=$(cat /proc/self/cgroup | grep "docker" | sed 's/^.*\///' | tail -n1)
          echo "Captured Container SHA256 ID: $CONTAINER_SHA256"
          echo "CONTAINER_SHA256=$CONTAINER_SHA256" >> $GITHUB_ENV

      # Step 2: Validate Docker Container SHA256 ID
      - name: Validate Docker Container SHA256 ID
        run: |
          EXPECTED_CONTAINER_SHA256="${{ secrets.CONTAINER_SHA256 }}"
          if [[ "$CONTAINER_SHA256" != "$EXPECTED_CONTAINER_SHA256" ]]; then
            echo "Error: Docker Container SHA256 ID does not match. Aborting."
            exit 1
          else
            echo "Docker Container SHA256 ID matches. Proceeding..."
          fi

      # Step 3: Log Node version and OS release
      - name: Log the Node version and OS release
        run: |
          node -v
          cat /etc/os-release
