name: Docker Container as Agent
on: 
  push: 
    branches: 
      - main
jobs:  
  docker-agent:    
    # runs-on: ubuntu-latest    
    container:      
      image: dheeman29/test:v1
    steps:      
      # Step 1: Pull Docker Image
      - name: Pull Docker Image        
        run: |          
          docker pull dheeman29/test:v1

      # Step 2: Capture SHA256 ID of the Image
      - name: Capture SHA256 ID of the Image
        run: |          
          CONTAINER_SHA256=$(docker inspect --format='{{index .RepoDigests 0}}' dheeman29/test:v1 | sed 's/.*@sha256://')
          echo "CONTAINER_SHA256=$CONTAINER_SHA256" >> $GITHUB_ENV

      # Step 3: Verify Container SHA256 ID
      - name: Verify Container SHA256 ID        
        run: |          
          EXPECTED_SHA256="${{ secrets.EXPECTED_SHA256 }}"
          ACTUAL_SHA256="${{ env.CONTAINER_SHA256 }}"
          
          if [ "$EXPECTED_SHA256" != "$ACTUAL_SHA256" ]; then
              echo "SHA256 mismatch. Aborting."
              exit 1
          fi
          echo "SHA256 ID verified successfully."

      # Step 4: Print Hello World from the Container
      - name: Hello World        
        run: |          
          echo "Hello World from container agent!"

  
