name: Build, Validate Docker Image and Container

on:
  push:
    branches:
      - main

jobs:
  # Job 1: Build Docker image and capture the SHA256 digest
  build-image:
    runs-on: ubuntu-latest  # Runs in a containerized environment, not a VM
    container:
      image: docker:latest  # Runs the job inside a Docker container
    steps:
      # Step to check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3  # Ensure you pull the latest code, including the Dockerfile

      # Step to set up Docker environment
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step to build Docker image and capture SHA256 digest
      - name: Build Docker Image
        run: |
          docker build --no-cache -t myapp:latest .
          IMAGE_ID=$(docker inspect --format='{{.ID}}' myapp:latest)  # Capture the Image ID (SHA256)
          echo "IMAGE_ID=${IMAGE_ID}" >> $GITHUB_ENV  # Store Image ID for use in next jobs

      - name: Display Image ID
        run: echo "Built Image ID is ${{ env.IMAGE_ID }}"
