name: Docker Container as Agent
on:
  push:
    branches:
      - main
jobs:
  docker-agent:
    runs-on: ubuntu-latest
    container:
      image: dheeman29/docker-cosign@sha256:${{ secrets.EXPECTED_SHA256 }}  # Use SHA256 from secrets
    permissions:
      contents: read
      security-events: write
    steps:
      # Step to verify the Container SHA256 ID
      - name: Verify Container SHA256 ID
        run: |
          EXPECTED_SHA256="${{ secrets.EXPECTED_SHA256 }}"
          ACTUAL_SHA256=$(docker inspect --format='{{index .RepoDigests 0}}' dheeman29/docker-cosign@sha256:$EXPECTED_SHA256 | sed 's/.*@sha256://')
          if [ "$EXPECTED_SHA256" != "$ACTUAL_SHA256" ]; then
              echo "SHA256 mismatch. Aborting."
              exit 1
          fi
          echo "SHA256 ID verified successfully."

      # Step to log in to Docker Hub
      - name: Log in to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          echo "Attempting Docker login"
          echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      # Step to run Trivy Vulnerability Scanner
      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: dheeman29/docker-cosign@sha256:${{ secrets.EXPECTED_SHA256 }}  # Use SHA256 for Trivy scan
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      # Step to upload Trivy scan results to GitHub Security Tab
      - name: Upload Trivy Scan Results to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step to verify Image Signature (Key-based)
      - name: Verify Image Signature (Key-based)
        run: |
          cosign verify --key cosign.pub dheeman29/docker-cosign@sha256:${{ secrets.EXPECTED_SHA256 }}  # Use SHA256 for signature verification
        env:
          COSIGN_EXPERIMENTAL: "true"

      # Step to print Hello World from the Container
      - name: Hello World
        run: |
          echo "Hello World from container agent!"
